apiVersion: v1
kind: ConfigMap
metadata:
  name: dra-driver-cpu-sysfs-overlay-example
data:
  sysfs-overlay.yaml: |
    /sys/devices/system/cpu/online: "0-3\n"
    /sys/devices/system/cpu/smt/control: "off\n"
    /sys/devices/pci0000:00/pci_bus/0000:00/cpulistaffinity: "0-1\n"
    /sys/devices/pci0001:80/pci_bus/0001:80/cpulistaffinity: "2-3\n"
    /sys/devices/system/node/node0/cpulist: "0-1\n"
    /sys/devices/system/node/node1/cpulist: "2-3\n"
    /sys/devices/system/cpu/cpu0/node0: ""
    /sys/devices/system/cpu/cpu0/topology/physical_package_id: "0\n"
    /sys/devices/system/cpu/cpu0/topology/core_id: "0\n"
    /sys/devices/system/cpu/cpu0/topology/cluster_id: "0\n"
    /sys/devices/system/cpu/cpu0/cache/index3/level: "3\n"
    /sys/devices/system/cpu/cpu0/cache/index3/id: "0\n"
    /sys/devices/system/cpu/cpu0/cache/index3/shared_cpu_list: "0-1\n"
    /sys/devices/system/cpu/cpu1/node0: ""
    /sys/devices/system/cpu/cpu1/topology/physical_package_id: "0\n"
    /sys/devices/system/cpu/cpu1/topology/core_id: "1\n"
    /sys/devices/system/cpu/cpu1/topology/cluster_id: "0\n"
    /sys/devices/system/cpu/cpu1/cache/index3/level: "3\n"
    /sys/devices/system/cpu/cpu1/cache/index3/id: "0\n"
    /sys/devices/system/cpu/cpu1/cache/index3/shared_cpu_list: "0-1\n"
    /sys/devices/system/cpu/cpu2/node1: ""
    /sys/devices/system/cpu/cpu2/topology/physical_package_id: "1\n"
    /sys/devices/system/cpu/cpu2/topology/core_id: "0\n"
    /sys/devices/system/cpu/cpu2/topology/cluster_id: "0\n"
    /sys/devices/system/cpu/cpu2/cache/index3/level: "3\n"
    /sys/devices/system/cpu/cpu2/cache/index3/id: "1\n"
    /sys/devices/system/cpu/cpu2/cache/index3/shared_cpu_list: "2-3\n"
    /sys/devices/system/cpu/cpu3/node1: ""
    /sys/devices/system/cpu/cpu3/topology/physical_package_id: "1\n"
    /sys/devices/system/cpu/cpu3/topology/core_id: "1\n"
    /sys/devices/system/cpu/cpu3/topology/cluster_id: "0\n"
    /sys/devices/system/cpu/cpu3/cache/index3/level: "3\n"
    /sys/devices/system/cpu/cpu3/cache/index3/id: "1\n"
    /sys/devices/system/cpu/cpu3/cache/index3/shared_cpu_list: "2-3\n"
